### ISSUE TITLE
Module not found error during initial build

### ISSUE THREAD

**Issue by ethul** [ethul/purs-loader#15]
```bash
ERROR in ./src/Foo.purs
Module not found: Error: Cannot resolve module 'Foo' in
/path/src
 @ ./src/Foo.purs 1:17-31
```

Typically, the purescript files are compiled to a separate output directory outside of the source directory. This requires the output directory to be specified in the webpack configuration file in the `resolve.modulesDirectories` array so that webpack will pick up the compiled javascript modules. 

However, the first time that purescript compiles, the output directory may not yet exist. In this case, webpack will not register the output directory, resulting in the error seen above. To work around this, we can create the output directory before webpack runs. Even if it is an empty directory, it will resolve this issue.

Further investigation is necessary to determine how to do this in the loader. The user must do this outside of the loader currently.

**Comment by natefaubion** [comment]
Perhaps when building, we should fix the `require-path` to be `../`, and when creating the temporary dependency for webpack, we should reference an absolute path to the output directory instead of expecting the build path to be in `modulesDirectories`? That way we don't get any conflicts between npm modules and purescript modules (like 'react' in npm vs 'React' for ps). Thoughts?

**Comment by ethul** [comment]
I think you are on to a good solution. I did something like this on a
project and it is working well. I think applying something like that here
would be ideal. The conflicts are definitely an issue.
