### ISSUE TITLE
PSC is spawned on each import

### ISSUE THREAD

**Issue by natefaubion** [ethul/purs-loader#32]
Every time you import a `.purs` file it spawns a `psc` process. This is mostly harmless, though creates a lot of unnecessary work and will extend your build times as `psc` still has to go through and check which files need to be recompiled.

Maybe we should write the loader to only emit the shim module, then use a plugin to do all the work at the appropriate point in the pipeline? This would also let us work in #31 as an option. What do you think?

**Comment by ethul** [comment]
I definitely think a plugin is a good idea. This has crossed my mind in the past, but I haven't really explored it at all yet. Also, leveraging psc-bundle as you mention in #31 would be awesome. There are a few details I think I need to understand a bit better, but overall I think you are on to a great approach to integrate purescript with webpack.

On a side note, one detail I am curious about is using this with webpack's code splitting feature. Do you have any thoughts on this? I admit I haven't really used code-spitting very much, so maybe I just need to look into this further to get a better idea of how everything fits together.

In any case, this is all sounding like a great improvement to the purs-loader!

**Comment by natefaubion** [comment]
> I definitely think a plugin is a good idea. This has crossed my mind in the past, but I haven't really explored it at all yet. Also, leveraging psc-bundle as you mention in #31 would be awesome. There are a few details I think I need to understand a bit better, but overall I think you are on to a great approach to integrate purescript with webpack.

I've mostly got a POC working, and I think the change to a plugin is an improvement. I'm also thinking about making a PR to `psc-bundle` to just output to a new directory instead of stdout so you only get the DCE.

> On a side note, one detail I am curious about is using this with webpack's code splitting feature. Do you have any thoughts on this? I admit I haven't really used code-spitting very much, so maybe I just need to look into this further to get a better idea of how everything fits together.

AFAIK, it should just work, but you'll have to do all the coordination outside of your PureScript because the module loading is async using `require.ensure`. I've only used the `CommonChunksPlugin`, which should just work as well.

**Comment by ethul** [comment]
Awesome! I am very interested to take a look if you have the code available online. Good call on the `psc-bundle` feature to output a new directory. Noted on the code-splitting. I think I just have to give it all a go. Sounds good .

**Comment by natefaubion** [comment]
Sure https://gist.github.com/natefaubion/060609fee9876a27d143

It's in JS currently, and only works with master `psc-bundle`. You have to make sure the output dir doesn't have a bundle.js in it as well. I haven't figured out how to resolve the contents of a file without hitting disk. Trying to follow Webpack internals is like unraveling the world's largest ball of Christmas lights.

**Comment by ethul** [comment]
Thanks for the gist. Noted on the bundle.js.

**Comment by ethul** [comment]
I've been thinking on the psc spawning issue and I wonder if good solution might be to avoid spawning psc from a webpack loader or plugin altogether.

I admit I haven't entirely worked out this idea, but the purs-loader would essentially only emit the shim modules. Any running of psc must be handled in some other way. For example, I currently fire up pulp in watch mode and then run webpack in watch mode. Any changes to the purs files are picked up and built by pulp calling psc, and since the shim created by the purs-loader requires the psc-generated output, webpack is triggered and rebuilds the bundle.

We can potentially streamline this by using a plugin to perhaps start-up pulp in watch mode very early in webpack's init (just guessing this is a possibility) to kick things off. I think it would be nice if this command to be run in the init is arbitrary. Basically what-ever the command is, it would have to watch and build the project's purescript files. However, we'd still need to keep track of the output from psc to show errors, etc. to the user.
