### ISSUE TITLE
Relay psc errors to stderr instead of to webpack

### ISSUE THREAD

**Issue by natefaubion** [ethul/purs-loader#40]
When you get a nice, big compile error, it currently gets sent to webpack's errback, which means that it prints out everything in bold red, making it difficult to read. Additionally, I'd like to be able to use `psa` for output https://github.com/ethul/purescript-webpack-plugin/issues/10 and it's colors would get clobbered. I think it would be nicer to just print it out to stderr, and give a simple "compilation failed" message to webpack.

**Comment by ethul** [comment]
Good idea. I've been thinking the bold red error message is a bit much. I think jut writing it to stderr would be a nice change.

**Comment by ethul** [comment]
I was trying this out and the only drawback I see here is that if we output the error to stderr, it appears above the resulting webpack output. For example:
```
Error found:
at ../src/Two.purs line 3, column 9 - line 3, column 9

  Unable to parse module:
  unexpected "\n"
  expecting string character or end of string


See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information,
or to contribute content related to this error.

Hash: df499aee444c74d7958b
Version: webpack 1.12.14
Time: 273ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.65 kB       0  [emitted]  inner
    + 2 hidden modules

ERROR in ./src/Main.purs
Module build failed: Error: PureScript compilation has failed.
    at ...
```

While this is not a problem with one asset as above, if there are many, then one might have to scroll up to see the compilation error. Maybe there is a way to omit the list of generated assets in webpack? If so, this might be a good option to recommend to more easily see the compile errors.

Also, due to the way the loader does the compiling, it says `ERROR in ./src/Main.purs`, while the error is really in `Two.purs` as indicated in the purescript error message. And maybe it is not a huge deal, but I am not sure yet if there is a good way to align the errors.

**Comment by osener** [comment]
Hi @ethul, first of all I'm sorry for not following up on #37, I wasn't able to create a minimal testcase so I had to put [my project](https://github.com/osener/redux-purescript-example) online first, the latest versions seem to work perfectly. Thanks for your great work, my usecase wouldn't be possible without purs-loader.

The only problem I'm having is that after this change error reporting got a bit inconvenient, at least when I'm requiring PureScript modules from JS. 

Here's what I'm seeing now:
![tmpimg](https://cloud.githubusercontent.com/assets/111265/14066204/3cde4f04-f44c-11e5-97cf-53544e0bdd33.png)

I used to get the compiler output in the browser display instead of the "PureScript compilation has failed." message, and I need to scroll past the stack trace and 674 more lines before I can see the terminal output. On the flip-side, colorful psa output is very nice, and if there's no error PureScript warnings show up nicely without all that noise.

Anyhow, would you be open to reconsidering this or making it configurable?

**Comment by ethul** [comment]
@osener That's great things are working with the purs-loader for your project. I am glad to hear it!

Regarding the reporting of compiler errors, I was on the fence about this one. But I do think that the way we have it makes the most sense. I'd be happy to discuss this further, but essentially, since the plugin is actually running the compilation, I think it works nicely that it is the one to report the error.

That being said, I realize scrolling 674 lines is less than ideal. Perhaps a webpack config solution might work for you to alleviate the scrolling. In webpack/webpack#1191, there are a few suggestions describing how to quiet the output generated by webpack. I've found that doing something like the following does the trick for me. Note that this is using the webpack-dev-server, but there should be ways to do this with only webpack.

```javascript
var config = {
  devServer: {
    stats: {
      assets: false,
      colors: true,
      children: false,
      chunks: false,
      modules: false
    }
  },
  // rest of config
}
```

Let me know if something like the above config change might work for you. If not, I'd be happy to talk about other options here, and possibly adding an option as you suggest.

**Comment by osener** [comment]
@ethul I tried it for a while and it makes errors much easier to follow, thanks! 
![screenshot from 2016-04-04 22-06-39](https://cloud.githubusercontent.com/assets/111265/14259874/9f0462ac-fab1-11e5-9a31-79c91319769d.png). 

Though I still miss being able to see compiler errors in my browser, like in my screenshot or with [redbox-react](https://github.com/KeywordBrain/redbox-react), instead of having to check the terminal output. I really like hot reloading & instant feedback in the browser, so I'd love to have the old behavior as an option.

**Comment by ethul** [comment]
@osener Glad that the config change worked!

I think you bring up a good point about being able to show errors in the browser and use tools like redbox-react. I've raised issue ethul/purescript-webpack-plugin#18 to track this on the plugin. I think, if possible, I'd like to have this feature there. I will investigate this a bit further to see what we can do. I am open to suggestions and ideas though.

**Comment by osener** [comment]
Awesome, thanks for reconsidering it!

**Comment by ethul** [comment]
Welcome!
